"""Edge auto-healing — Cloudflare Worker / Vercel Edge / WordPress patch generation."""
from __future__ import annotations


def build_edge_patch(chain, fallback_url: str = "https://www.example.com/alternative-offer?subid=fallback") -> dict:
    needs_patch = (not chain.chain_ok) or (not chain.params_intact) or (chain.final_status and chain.final_status >= 400)
    if not needs_patch:
        return {"needed": False}
    src_path = "/" + chain.source_url.split("/", 3)[-1] if "://" in chain.source_url else chain.source_url
    cf_worker = f"""// Auto-generated by iGaming-Redirect-Pathfinder — {chain.source_url}
addEventListener('fetch', event => {{ event.respondWith(handle(event.request)); }});
async function handle(req) {{
  const url = new URL(req.url);
  if (url.pathname === '{src_path}' || req.url === '{chain.source_url}') {{
    return Response.redirect('{fallback_url}', 302);
  }}
  return fetch(req);
}}"""
    vercel_edge = f"""// middleware.js — auto-generated edge reroute
import {{ NextResponse }} from 'next/server';
export function middleware(req) {{
  if (req.nextUrl.pathname === '{src_path}') {{
    return NextResponse.redirect('{fallback_url}');
  }}
}}
export const config = {{ matcher: ['{src_path}'] }};"""
    wp_rule = f"# WP Redirection (auto-generated)\n# Source: {chain.source_url}\n# Reason: {chain.broken_reason or 'param-loss/broken-chain'}\nRedirect 302 {src_path} {fallback_url}"
    patch = {"needed": True, "fallback_url": fallback_url, "cloudflare_worker_js": cf_worker,
             "vercel_edge_js": vercel_edge, "wordpress_redirect": wp_rule}
    chain.edge_patch = patch
    return patch


def build_vendor_ticket(chain) -> str:
    stripped = [e.param for e in chain.param_events if e.status != "survived"]
    ticket = (f"Subject: Tracking failure on {chain.expected_operator} — {chain.geo} / {chain.device}\n\n"
              f"Hi {chain.expected_operator.title()} Affiliate Team,\n\n"
              f"Our monitor traced {chain.source_url}\n"
              f"Final URL: {chain.final_url} (HTTP {chain.final_status})\n"
              f"Chain length: {len(chain.hops)} hops, total latency {chain.latency.total_ms:.0f} ms\n"
              f"Stripped/mutated params: {', '.join(stripped) if stripped else 'none'}\n"
              f"Broken reason: {chain.broken_reason or 'n/a'}\n"
              f"Hops:\n" + "\n".join(f"  {h.index}. [{h.status}] {h.url} ({h.total_ms:.0f} ms)" for h in chain.hops) +
              f"\n\nPlease confirm tracking domain health and S2S fallback.\n\n— Publisher Affiliate Engineering")
    chain.vendor_ticket = ticket
    return ticket
