"""Single source of truth for all documentation pages.

The info pages (About, Why 2026, Features, Inputs, Outputs, Impact) render
directly from this file via GET /content — so when the tool gains a feature,
updating THIS file updates every page automatically. No per-page edits, no drift.
"""
from __future__ import annotations

NAV = [
    ("about", "About the tool"),
    ("why2026", "Why this tool in 2026"),
    ("features", "Core features & subfunctions"),
    ("inputs", "Inputs the tool needs"),
    ("outputs", "Outputs to expect"),
    ("impact", "Business impact"),
]

SECTIONS = {
    "about": {
        "title": "About the tool",
        "subtitle": "Outbound Affiliate Link Chain & Latency Tracker",
        "intro": ("An enterprise-grade technical SEO, compliance and revenue-protection platform "
                  "for high-volume iGaming publishers, affiliate networks and operators. A single click on an "
                  "offer button routes through publisher cloaking plugins, analytics handlers, affiliate ad servers, "
                  "geo/compliance routers and operator attribution — this tool continuously crawls, executes, "
                  "simulates and audits those multi-hop chains under hyper-realistic browsing conditions, catching "
                  "broken links, dropped tracking parameters, latency bottlenecks and regulatory violations before "
                  "they burn commission revenue."),
        "blocks": [
            {"h": "What it does in one run",
             "text": "Paste any publisher URL (or upload targets three ways), press Run, and watch a live log as the engine traces every redirect hop, fingerprints parameter survival, profiles per-hop latency, scrapes compliance disclosures, simulates ad-blockers, inspects deep-links, checks brand alignment and bonus parity — then delivers revenue, engineering and legal outputs.",
             "bullets": []},
            {"h": "Who it serves",
             "text": "",
             "bullets": ["Affiliate & SEO teams — action center, JIRA tickets, edge patches",
                         "VP Revenue — dollars-at-risk dashboard, health index, SLA leverage",
                         "Legal & compliance — violation logs, geo-mismatch logs, disclosure audits",
                         "Engineering — hop maps, timings, vendor-ready tickets"]},
            {"h": "How it stays honest",
             "text": "Every number on screen comes from live HTTP measurements taken during your run. Estimates (click reach-scaling, EPC defaults) are always labelled as estimates.",
             "bullets": []},
        ],
    },
    "why2026": {
        "title": "Why this tool requirement exists in 2026",
        "subtitle": "iGaming infrastructure is a different beast",
        "intro": ("A basic cURL checker gets roasted by enterprise SEO teams within five minutes. 2026 iGaming "
                  "runs on dynamic cloaking, geo-fencing, edge routing, strict regional disclosures and aggressive "
                  "bot mitigation — links break silently while the site stays up and the revenue pipeline dies."),
        "blocks": [
            {"h": "The forces making it mandatory", "text": "", "bullets": [
                "Operator migrations between affiliate platforms (Cellxpert, Income Access, NetRefer, Everflow) silently strip IDs",
                "Regional ISP blocks and licence-jurisdiction routing send users to wrong/offshore landers",
                "JavaScript redirects, meta-refresh and canvas-fingerprint challenges defeat header-only checkers",
                "Cloudflare / Datadome / Akamai bot walls block naive crawlers mid-chain",
                "Regulators (UKGC, NJ DGE, AGCO) fine publishers for missing RG disclosures and mismatched promos",
                "Privacy browsers + ad-blockers (Brave, Safari ITP, uBlock) kill tracking subdomains for 10–20% of users",
                "Marquee events (Super Bowl, March Madness) crash operator links under load — zero-revenue downtime",
            ]},
        ],
    },
    "features": {
        "title": "Core features, functions & subfunctions",
        "subtitle": "10 engines, one run",
        "intro": "Page 2 of the tool renders a dedicated section (F1–F10) for each engine below, computed live from your targets.",
        "blocks": [
            {"h": "F1 · Multi-Hop Asynchronous Tracing Engine (HTTP + Headless)",
             "text": "Hybrid crawler: fast HTTP header tracer for clean 301/302s, auto-escalating to headless on JS redirects.",
             "bullets": ["Step-by-step chain map with 301/302/303/307/308/200/404/500 per hop",
                         "Intermediate IPs, server headers and DNS times per hop",
                         "Meta-refresh + window.location detection, bot-wall signals"]},
            {"h": "F2 · Dynamic Tracking Parameter Loss Fingerprinting",
             "text": "Hop-by-hop query-param mutation audit from click to lander.",
             "bullets": ["Survived / stripped / mutated verdict per affiliate ID and sub-ID",
                         "Silent-stripping alerts (present hop 1, gone hop 3)",
                         "Operator → tracking-network routing verification"]},
            {"h": "F3 · Geo-Fenced Edge & Latency Profiler",
             "text": "Jurisdiction-pinned execution with forensic timing.",
             "bullets": ["DNS / TCP+TLS / TTFB / download split per hop",
                         "User drop-off scoring vs 1800 ms 4G threshold",
                         "Residential proxy routing notes per licence geo"]},
            {"h": "F4 · Automated Compliance & License Guardian",
             "text": "Regulatory footer scraper + geo-routing auditor + expired-offer NLP.",
             "bullets": ["Required RG strings and licence badges per geo pack",
                         "Geo-mismatch detection (UK click → offshore .com lander)",
                         "Soft-404 detection on 200-OK expired promos"]},
            {"h": "F5 · Bot Mitigation & Anti-Evasion Bypassing",
             "text": "Fingerprint-spoofed headers, proxy rotation, headless escalation.",
             "bullets": ["Canvas/WebGL/header/TLS realism per device profile",
                         "Cloudflare / Datadome / Akamai challenge handling"]},
            {"h": "F6 · Dynamic Auto-Healing / Edge Link Rerouting",
             "text": "Zero lost traffic while the CMS fix lands.",
             "bullets": ["Copy-paste Cloudflare Worker, Vercel Edge and WordPress rules",
                         "Triggered by 404s, param loss and expired promos"]},
            {"h": "F7 · Ad-Blocker & Privacy Bypass Auditor",
             "text": "Simulates uBlock / EasyList / Brave / Safari ITP / Firefox ETP.",
             "bullets": ["Tracking-subdomain kill detection per chain",
                         "Site-wide vulnerability percentage"]},
            {"h": "F8 · Deep-Linking & App Store Route Inspection",
             "text": "Mobile-only verdicts on native app routing.",
             "bullets": ["App-scheme, universal-link and store-fallback detection",
                         "Broken web-view degradation flags"]},
            {"h": "F9 · AI Landing-Page Sentiment & Brand Alignment",
             "text": "Confirms the lander brand matches the review page.",
             "bullets": ["Expected-brand presence check, rival-brand detection",
                         "Misroute guard (BetMGM review → DraftKings lander)"]},
            {"h": "F10 · Competitive Offer Discrepancy Engine",
             "text": "On-site bonus pitch vs live lander text.",
             "bullets": ["Parsed offer comparison (deposit/get amounts)",
                         "Trust + advertising-standards violation flags"]},
        ],
    },
    "inputs": {
        "title": "Inputs the tool needs",
        "subtitle": "10 layers (Layer 0 auto-fills them from any URL)",
        "intro": "Enterprise audits need more than URL submission. Page 1 collects all ten layers; Layer 0 (site auto-fill) researches any website and pre-fills them with verified live data.",
        "blocks": [
            {"h": "1 · Site crawl & target discovery",
             "text": "Sitemaps, pasted lists and CSV uploads merge into one queue.",
             "bullets": ["XML sitemap / index URLs (auto-expanded, verified live)",
                         "Direct URL lists + bulk CSV (source, anchor, operator, network, geo, device, clicks, EPC, bonus)",
                         "Crawl constraints: user-agents, concurrency, depth, path exclusions"]},
            {"h": "2 · Affiliate tracking & parameter rule engine",
             "text": "Regexes that must survive every hop.",
             "bullets": ["Primary IDs (btag|affid|clickid|a_aid|cmp), sub-IDs, promo codes",
                         "Operator → tracking-network mappings (auto-mined from observed domains)"]},
            {"h": "3 · Simulation & execution environment",
             "text": "Hyper-realistic browsing conditions.",
             "bullets": ["Geo nodes per licence jurisdiction (NJ / UK / Ontario)", "Device profiles (iOS, Android, desktop)",
                         "HTTP-only vs hybrid vs always-headless execution"]},
            {"h": "4 · Regulatory & compliance rules",
             "text": "Region-specific disclosure packs.",
             "bullets": ["Mandatory strings (21+, BeGambleAware.org, 1-800-GAMBLER…)", "Licence badges (UKGC, NJ DGE, AGCO…)", "Soft-404 phrase lists"]},
            {"h": "5 · Business data & revenue context",
             "text": "Turns technical failures into dollars.",
             "bullets": ["GA4/Search Console clicks per URL (30d)", "Per-operator EPC baselines"]},
            {"h": "6 · Affiliate program API credentials",
             "text": "Session-only live sync hooks for Cellxpert, Income Access, NetRefer, MyAffiliates, Everflow.",
             "bullets": []},
            {"h": "7 · Ad-blocker & privacy rule feeds",
             "text": "uBlock Origin, EasyList, Brave Shields, Safari ITP, Firefox ETP toggles.",
             "bullets": []},
            {"h": "8 · Live operator promotional feeds",
             "text": "API/RSS/JSON bonus feeds (auto-discovered via RSS autodiscovery).",
             "bullets": []},
            {"h": "9 · Server log files (CDN & edge logs)",
             "text": "Cloudflare/Fastly log lines counted for /out/ /go/ click events; auto-generated filter recipe included.",
             "bullets": []},
            {"h": "10 · Historical conversion baselines",
             "text": "Click-to-register and click-to-deposit rates per operator, ranked by observed frequency.",
             "bullets": []},
        ],
    },
    "outputs": {
        "title": "Outputs to expect",
        "subtitle": "9 outputs for revenue, engineering and legal",
        "intro": "Page 3 renders every output below from the same live run — downloadable as real PDF, CSV and JSON.",
        "blocks": [
            {"h": "O1 · Executive revenue risk dashboard",
             "text": "Dollars at risk (clicks × EPC), 0–100 health index, regs/deposits-lost estimates.",
             "bullets": []},
            {"h": "O2 · Technical SEO & engineering action center",
             "text": "Interactive hop maps, failure points, JIRA/Trello/ClickUp-ready tickets, CSV/JSON exports.",
             "bullets": []},
            {"h": "O3 · Latency & Core Web Vitals impact report",
             "text": "Network speed scorecard plus redirect-overhead vs LCP-budget penalty matrix.",
             "bullets": []},
            {"h": "O4 · Regulatory & legal risk audit report",
             "text": "Compliance violation log and geo-mismatch log with missing-string detail.",
             "bullets": []},
            {"h": "O5 · Enterprise alerting & webhooks",
             "text": "Slack/Teams payloads for broken high-value links plus a daily email digest preview.",
             "bullets": []},
            {"h": "O6 · Auto-generated edge patch rules",
             "text": "Cloudflare Worker / Vercel Edge / WordPress redirects with copy buttons.",
             "bullets": []},
            {"h": "O7 · Ad-blocker vulnerability scorecard",
             "text": "Percentage of paths failing under privacy tools, per-chain blocked hosts.",
             "bullets": []},
            {"h": "O8 · Ad network SLA performance matrix",
             "text": "Uptime, latency and survival per tracking partner — renewal leverage.",
             "bullets": []},
            {"h": "O9 · Automated vendor ticket generation",
             "text": "Operator-ready escalation emails with hop evidence and latency data.",
             "bullets": []},
        ],
    },
    "impact": {
        "title": "Business impact",
        "subtitle": "Quantifiable ROI across five units",
        "intro": "Why enterprises pay SaaS money for this instead of running a cURL script.",
        "blocks": [
            {"h": "Revenue protection", "text": "",
             "bullets": ["Zero lost commissions from stripped IDs and silent 404s",
                         "Higher click-to-register conversion via latency removal",
                         "Edge rerouting saves marquee-event traffic during outages",
                         "10–20% commission recovery from ad-blocked users"]},
            {"h": "Operational efficiency", "text": "",
             "bullets": ["90%+ less manual QA across tens of thousands of links",
                         "Zero-diagnosis developer triage with exact failure points"]},
            {"h": "Legal shielding", "text": "",
             "bullets": ["Fewer UKGC / state-board fines via disclosure and geo audits",
                         "No mismatched promos or un-localised landers slipping through"]},
            {"h": "Partner leverage", "text": "",
             "bullets": ["Hard SLA data for network fee and commission negotiations",
                         "Evidence-backed demands for S2S integrations and infra fixes"]},
        ],
    },
}
